x-app-config: &app_config
  build:
    context: .
    dockerfile: Dockerfile-development
    args:
      RUBY_VERSION: ${SF_RUBY_VERSION}
version: '3'
services:
  web:
    <<: *app_config
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - .:/app:cached
      - bundle_cache:/bundle
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password

  db:
    image: postgres
    restart: always
    volumes:
      - database_data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres


volumes:
  database_data:
  bundle_cache:
